name: Fyne-Cross Multi-Arch Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Multiple Architectures
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Create .env file from secrets
      run: |
        echo "INTERNET_TEST_IP=${{ secrets.INTERNET_TEST_IP }}" >> .env
        echo "INTRANET_PUBLIC_IP=${{ secrets.INTRANET_PUBLIC_IP }}" >> .env
        echo "WIREGUARD_PORT=${{ secrets.WIREGUARD_PORT }}" >> .env
        echo "INTRANET_HEALTHCHECK=${{ secrets.INTRANET_HEALTHCHECK }}" >> .env
        echo "SAMBA_SERVER_IP=${{ secrets.SAMBA_SERVER_IP }}" >> .env
        echo "SAMBA_USER=${{ secrets.SAMBA_USER }}" >> .env
        echo "SAMBA_PASSWORD=${{ secrets.SAMBA_PASSWORD }}" >> .env

    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Build for Windows 64-bit
      run: |
        fyne-cross windows -arch amd64 -app-id "com.pfr.intracheck" -icon "icon.png" -output intranet-check-windows-amd64.exe
        mkdir -p build
        unzip fyne-cross/dist/windows-amd64/intranet-check-windows-amd64.exe.zip -d build/

    - name: Build for macOS x86_64
      run: |
        fyne-cross darwin -arch amd64 -app-id "com.pfr.intracheck" -icon "icon.png" -output intranet-check-macos-amd64.app
        mkdir -p build
        unzip fyne-cross/dist/darwin-amd64/intranet-check-macos-amd64.app.zip -d build/

    - name: Build for macOS ARM64
      run: |
        fyne-cross darwin -arch arm64 -app-id "com.pfr.intracheck" -icon "icon.png" -output intranet-check-macos-arm64.app
        mkdir -p build
        unzip fyne-cross/dist/darwin-arm64/intranet-check-macos-arm64.app.zip -d build/

    - name: Archive artifacts
      run: |
        zip -r build/intranet-check-windows-amd64.zip build/intranet-check-windows-amd64.exe
        zip -r build/intranet-check-macos-amd64.zip build/intranet-check-macos-amd64.app
        zip -r build/intranet-check-macos-arm64.zip build/intranet-check-macos-arm64.app
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/*.zip
